"""
export_utils.py — JPG and fully-editable PPTX export.

PPTX design:
 - Title slide with key stats table
 - One content slide per chart (image + editable text boxes)
 - All titles, insights, and annotations are editable text — not baked into images
 - Summary slide at end with key findings table
"""

import io
import plotly.io as pio
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.oxml.ns import qn
from lxml import etree

# ── Brand colours ─────────────────────────────────────────────────────────────
BRAND_DARK   = RGBColor(0x0B, 0x1D, 0x3A)
BRAND_BLUE   = RGBColor(0x1E, 0x40, 0xAF)
BRAND_PURPLE = RGBColor(0x43, 0x38, 0xCA)
BRAND_LIGHT  = RGBColor(0xEE, 0xF2, 0xF7)
WHITE        = RGBColor(0xFF, 0xFF, 0xFF)
DARK_TEXT    = RGBColor(0x0F, 0x17, 0x2A)
MID_TEXT     = RGBColor(0x37, 0x41, 0x51)
LIGHT_TEXT   = RGBColor(0x94, 0xA3, 0xB8)

W  = Inches(13.333)   # slide width  (widescreen 16:9)
H  = Inches(7.5)      # slide height


def _para(tf, text, size=12, bold=False, italic=False,
          color=DARK_TEXT, align=PP_ALIGN.LEFT):
    """Add a paragraph to a text frame."""
    p = tf.add_paragraph()
    p.alignment = align
    run = p.add_run()
    run.text = text
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.italic = italic
    run.font.color.rgb = color
    run.font.name = "Calibri"
    return p


def _textbox(slide, left, top, width, height, text="", size=12, bold=False,
             italic=False, color=DARK_TEXT, align=PP_ALIGN.LEFT, word_wrap=True):
    """Add an editable text box to a slide."""
    txb = slide.shapes.add_textbox(left, top, width, height)
    tf  = txb.text_frame
    tf.word_wrap = word_wrap
    if text:
        _para(tf, text, size=size, bold=bold, italic=italic, color=color, align=align)
    return txb, tf


def _rect(slide, left, top, width, height, fill_color, line=False):
    """Add a solid rectangle shape."""
    shape = slide.shapes.add_shape(1, left, top, width, height)
    shape.fill.solid()
    shape.fill.fore_color.rgb = fill_color
    if not line:
        shape.line.fill.background()
    shape.shadow.inherit = False
    return shape


def fig_to_png(fig, w=1600, h=900) -> bytes | None:
    try:
        return pio.to_image(fig, format="png", width=w, height=h, scale=2)
    except Exception:
        return None


def fig_to_jpg(fig) -> bytes | None:
    try:
        return pio.to_image(fig, format="jpg", width=1400, height=800, scale=2)
    except Exception:
        return None


# ── Slide builders ─────────────────────────────────────────────────────────────

def _title_slide(prs, title, subtitle="", stats=None):
    """Gradient title slide with optional key-stats table."""
    blank = prs.slide_layouts[6]
    slide = prs.slides.add_slide(blank)

    # Full-bleed background
    bg = _rect(slide, 0, 0, W, H, BRAND_DARK)

    # Accent strip
    _rect(slide, 0, Inches(4.8), W, Inches(0.06), BRAND_BLUE)

    # App logo / icon area
    _textbox(slide, Inches(1.0), Inches(1.2), Inches(11), Inches(0.7),
             "📊  HR Analytics Platform",
             size=15, color=LIGHT_TEXT)

    # Main title
    _, tf = _textbox(slide, Inches(1.0), Inches(1.9), Inches(11), Inches(1.6))
    _para(tf, title, size=40, bold=True, color=WHITE)

    # Subtitle
    if subtitle:
        _textbox(slide, Inches(1.0), Inches(3.55), Inches(11), Inches(0.6),
                 subtitle, size=15, color=LIGHT_TEXT)

    # Stats table (if provided)
    if stats:
        tbl_left = Inches(1.0); tbl_top = Inches(5.1)
        tbl_w    = Inches(11.3); row_h   = Inches(0.42)
        n = len(stats)
        cell_w = tbl_w // n

        for i, (label, value) in enumerate(stats):
            x = tbl_left + i * cell_w
            # Value
            _textbox(slide, x, tbl_top, cell_w, row_h,
                     str(value), size=20, bold=True, color=WHITE)
            # Label
            _textbox(slide, x, tbl_top + Inches(0.42), cell_w, Inches(0.35),
                     label, size=10, color=LIGHT_TEXT)

    # Footer
    _textbox(slide, Inches(1.0), Inches(7.05), Inches(11), Inches(0.3),
             "Generated by HR Analytics Platform  ·  For internal use only",
             size=9, color=LIGHT_TEXT)

    return slide


def _chart_slide(prs, title, img_bytes, insight="", chart_number=1, total_charts=1):
    """
    One chart per slide.
    Layout:
      - Navy header bar (editable title text box)
      - Large chart image (left 62% of slide)
      - Right panel: editable insight, annotation area, chart number
      - Bottom: editable notes area
    All text elements are independently editable in PowerPoint.
    """
    blank = prs.slide_layouts[6]
    slide = prs.slides.add_slide(blank)

    # ── Header bar ──────────────────────────────────────────────────────────
    _rect(slide, 0, 0, W, Inches(0.80), BRAND_BLUE)

    # Chart number badge (top-right)
    _textbox(slide, Inches(12.1), Inches(0.12), Inches(1.0), Inches(0.55),
             f"{chart_number}/{total_charts}",
             size=10, color=WHITE, align=PP_ALIGN.RIGHT)

    # Editable title
    _, tf_title = _textbox(slide, Inches(0.3), Inches(0.10),
                           Inches(11.5), Inches(0.60))
    _para(tf_title, title, size=20, bold=True, color=WHITE)

    # ── Chart image (left 65%) ───────────────────────────────────────────────
    if img_bytes:
        slide.shapes.add_picture(
            io.BytesIO(img_bytes),
            Inches(0.15), Inches(0.88),
            width=Inches(8.6), height=Inches(5.65)
        )

    # ── Right panel ──────────────────────────────────────────────────────────
    panel_x = Inches(8.85)
    panel_w = Inches(4.30)

    # "Key Insight" heading
    _textbox(slide, panel_x, Inches(0.92), panel_w, Inches(0.35),
             "KEY INSIGHT", size=9, bold=True, color=LIGHT_TEXT)

    # Editable insight box
    insight_box, tf_ins = _textbox(
        slide, panel_x, Inches(1.28), panel_w, Inches(2.20),
        word_wrap=True
    )
    _para(tf_ins,
          insight if insight else "Add your interpretation of this chart here.",
          size=12, italic=True, color=DARK_TEXT)

    # Divider line
    _rect(slide, panel_x, Inches(3.55), panel_w, Inches(0.03), BRAND_LIGHT)

    # "Annotations" heading
    _textbox(slide, panel_x, Inches(3.62), panel_w, Inches(0.35),
             "ANNOTATIONS / ACTIONS", size=9, bold=True, color=LIGHT_TEXT)

    # Editable annotation area (blank, for user to fill in PowerPoint)
    ann_box, tf_ann = _textbox(
        slide, panel_x, Inches(3.98), panel_w, Inches(2.08),
        word_wrap=True
    )
    _para(tf_ann,
          "• Click here to add action items\n• Add context specific to your organisation\n• Note any follow-up required",
          size=11, color=MID_TEXT)

    # ── Bottom strip ─────────────────────────────────────────────────────────
    _rect(slide, 0, Inches(6.55), W, Inches(0.04), BRAND_LIGHT)

    _textbox(slide, Inches(0.15), Inches(6.62), Inches(8.7), Inches(0.75),
             "Notes:",
             size=9, bold=True, color=MID_TEXT)

    _, tf_notes = _textbox(slide, Inches(0.6), Inches(6.62), Inches(8.2), Inches(0.75))
    _para(tf_notes, "Click to add presenter notes for this chart.",
          size=10, color=LIGHT_TEXT)

    return slide


def _summary_slide(prs, insights_list):
    """
    Editable 'Key Findings' summary slide — uses a proper table,
    fully editable in PowerPoint.
    """
    blank = prs.slide_layouts[6]
    slide = prs.slides.add_slide(blank)

    _rect(slide, 0, 0, W, Inches(0.85), BRAND_DARK)
    _textbox(slide, Inches(0.35), Inches(0.12), Inches(12.6), Inches(0.62),
             "Key Findings Summary", size=24, bold=True, color=WHITE)

    if not insights_list:
        _textbox(slide, Inches(0.5), Inches(1.2), Inches(12.3), Inches(5.5),
                 "Add your key findings here.", size=14, color=DARK_TEXT)
        return slide

    # Two-column layout for insights
    col_w = Inches(6.2); gutter = Inches(0.3)
    y_start = Inches(1.0)

    left_x  = Inches(0.35)
    right_x = Inches(0.35) + col_w + gutter

    left_y  = y_start
    right_y = y_start

    for idx, item in enumerate(insights_list[:12]):
        emoji, headline, detail = (item if len(item)==3 else (item[0], item[1], ""))
        x = left_x if idx % 2 == 0 else right_x
        y = left_y if idx % 2 == 0 else right_y

        # Card background
        _rect(slide, x, y, col_w, Inches(0.95), BRAND_LIGHT)
        # Accent left stripe
        _rect(slide, x, y, Inches(0.06), Inches(0.95), BRAND_BLUE)

        # Text
        _, tf = _textbox(slide, x + Inches(0.15), y + Inches(0.07),
                         col_w - Inches(0.22), Inches(0.38))
        _para(tf, f"{emoji}  {headline}", size=11, bold=True, color=DARK_TEXT)

        _, tf2 = _textbox(slide, x + Inches(0.15), y + Inches(0.46),
                          col_w - Inches(0.22), Inches(0.40))
        _para(tf2, detail[:110] + ("…" if len(detail) > 110 else ""),
              size=9, color=MID_TEXT)

        if idx % 2 == 0: left_y  += Inches(1.05)
        else:             right_y += Inches(1.05)

    # Footer
    _rect(slide, 0, Inches(7.18), W, Inches(0.32), BRAND_DARK)
    _textbox(slide, Inches(0.35), Inches(7.20), Inches(12.6), Inches(0.25),
             "HR Analytics Platform  ·  All text in this report is editable in PowerPoint",
             size=8, color=LIGHT_TEXT)

    return slide


# ── Public API ─────────────────────────────────────────────────────────────────

def build_pptx(selections: list,
               report_title: str = "HR Analytics Report",
               insights_list: list = None) -> bytes:
    """
    Build an editable PPTX deck.

    selections: list of {title, fig, insight}
    insights_list: list of (emoji, headline, detail) tuples for summary slide
    """
    prs = Presentation()
    prs.slide_width  = W
    prs.slide_height = H

    # Key stats for title slide
    stats = []
    for item in selections[:5]:
        if item.get("insight"):
            # Extract first number-like token as a quick stat
            import re
            nums = re.findall(r'\d[\d,%.]+', item["insight"])
            if nums:
                stats.append((item["title"][:28], nums[0]))
    if not stats:
        stats = [("Charts", str(len(selections))), ("Report", "HR Analytics")]

    # ── Title slide ──────────────────────────────────────────────────────────
    _title_slide(prs, report_title,
                 subtitle="People Intelligence Report",
                 stats=stats[:6])

    # ── Content slides ───────────────────────────────────────────────────────
    total = len(selections)
    for i, item in enumerate(selections):
        img = fig_to_png(item.get("fig"))
        _chart_slide(
            prs,
            title         = item.get("title", f"Chart {i+1}"),
            img_bytes     = img,
            insight       = item.get("insight", ""),
            chart_number  = i + 1,
            total_charts  = total,
        )

    # ── Summary slide ────────────────────────────────────────────────────────
    _summary_slide(prs, insights_list or [])

    out = io.BytesIO()
    prs.save(out)
    out.seek(0)
    return out.getvalue()


def build_excel(df: "pd.DataFrame", col_map: dict, insights_list: list = None) -> bytes:
    """3-sheet formatted Excel: Employee Data, KPI Summary, Column Mapping."""
    import io as _io, pandas as pd
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    buf = _io.BytesIO()
    skip = {c for c in df.columns if c.startswith("__")}
    df_exp = df[[c for c in df.columns if c not in skip]].copy()
    for col in df_exp.columns:
        if pd.api.types.is_datetime64_any_dtype(df_exp[col]):
            df_exp[col] = df_exp[col].dt.date
    # KPI rows
    rows = []
    n = len(df)
    act_col = col_map.get("_is_active","__is_active")
    att_col = col_map.get("_attrition"); ten_col = col_map.get("_tenure_years")
    gen_col = col_map.get("gender");     sal_col = next((col_map.get(c) for c in ["salary"] if col_map.get(c)),None)
    rows.append(("Total Records", n, "All records in filter"))
    if act_col in df.columns:
        act = int((df[act_col]==1).sum())
        rows.append(("Active Employees", act, f"{act/n:.1%} of total"))
        rows.append(("Former Employees", n-act, f"{(n-act)/n:.1%} of total"))
    if att_col and att_col in df.columns:
        rows.append(("Attrition Rate", f"{df[att_col].mean():.1%}", "15% = industry benchmark"))
    if ten_col and ten_col in df.columns:
        rows.append(("Avg Tenure (yrs)", round(df[ten_col].mean(),1), ""))
    if gen_col and gen_col in df.columns:
        rows.append(("Female %", f"{(df[gen_col]=='Female').mean():.1%}", "30% = D&I target"))
    if sal_col and sal_col in df.columns:
        rows.append(("Median Pay", f"{df[sal_col].median():,.0f}", ""))
    if insights_list:
        for emoji,h,d in (insights_list or []):
            rows.append((f"{emoji} {h}", "", d[:120]))
    kpi_df = pd.DataFrame(rows, columns=["Metric","Value","Note"])
    map_df = pd.DataFrame([(k.replace("_"," ").title(),v) for k,v in col_map.items() if not k.startswith("_")],
                           columns=["HR Concept","Detected Column"])
    with pd.ExcelWriter(buf, engine="openpyxl") as writer:
        df_exp.to_excel(writer, sheet_name="Employee Data",  index=False)
        kpi_df.to_excel(writer, sheet_name="KPI Summary",    index=False)
        map_df.to_excel(writer, sheet_name="Column Mapping", index=False)
        wb = writer.book
        HFILL = PatternFill("solid", fgColor="1E40AF")
        AFILL = PatternFill("solid", fgColor="EFF6FF")
        HFONT = Font(name="Calibri", bold=True, color="FFFFFF", size=11)
        BFONT = Font(name="Calibri", size=11, color="0F172A")
        BSIDE = Side(style="thin", color="CBD5E1")
        BORD  = Border(bottom=BSIDE)
        def _style(ws, widths=None):
            for cell in ws[1]:
                cell.font=HFONT; cell.fill=HFILL
                cell.alignment=Alignment(horizontal="center",vertical="center")
            for ri,row in enumerate(ws.iter_rows(min_row=2),2):
                fill=AFILL if ri%2==0 else None
                for cell in row:
                    cell.font=BFONT; cell.border=BORD
                    cell.alignment=Alignment(horizontal="left",vertical="center",wrap_text=True)
                    if fill: cell.fill=fill
            if widths:
                for col,w in widths.items(): ws.column_dimensions[col].width=w
            else:
                for col in ws.columns:
                    mw=max((len(str(c.value or "")) for c in col),default=8)
                    ws.column_dimensions[col[0].column_letter].width=min(mw+4,40)
            ws.freeze_panes="A2"; ws.row_dimensions[1].height=22
        _style(wb["Employee Data"])
        _style(wb["KPI Summary"], {"A":"32","B":"18","C":"50"})
        _style(wb["Column Mapping"], {"A":"26","B":"32"})
        wb["Employee Data"].auto_filter.ref = wb["Employee Data"].dimensions
    buf.seek(0)
    return buf.getvalue()
