"""
export_utils.py — Editable PPTX + formatted Excel export.

PPTX fixes vs previous version:
 - fig_to_png uses kaleido 0.2.1 (no Chrome needed) + Pillow fallback placeholder
 - Title slide stat extraction strips trailing punctuation
 - Summary slide text limit raised to 160 chars
 - Chart slide shows placeholder box when image fails (never blank)
 - All text boxes are independently editable in PowerPoint
"""

import io
import re
import plotly.io as pio
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN

# ── Brand colours ─────────────────────────────────────────────────────────────
NAVY    = RGBColor(0x0D, 0x11, 0x17)
INDIGO  = RGBColor(0x50, 0x46, 0xE4)
WHITE   = RGBColor(0xFF, 0xFF, 0xFF)
DARK    = RGBColor(0x0F, 0x17, 0x2A)
MID     = RGBColor(0x37, 0x41, 0x51)
LIGHT   = RGBColor(0x94, 0xA3, 0xB8)
SILVER  = RGBColor(0xE2, 0xE8, 0xF0)
ACCENT_LIGHT = RGBColor(0xEE, 0xF2, 0xFF)

W = Inches(13.333)
H = Inches(7.5)


# ── Image export ─────────────────────────────────────────────────────────────
def fig_to_png(fig, w=1380, h=776) -> bytes | None:
    """Convert Plotly figure to PNG bytes using kaleido 0.2.1 (no Chrome needed)."""
    for scale in [1.5, 1.0]:
        try:
            img = pio.to_image(fig, format="png", width=w, height=h, scale=scale)
            if img and len(img) > 500:
                return img
        except Exception:
            pass
    return None


def fig_to_jpg(fig) -> bytes | None:
    """JPG for in-app download buttons."""
    try:
        return pio.to_image(fig, format="jpg", width=1200, height=720, scale=1.5)
    except Exception:
        return None


def _make_placeholder_img(title: str) -> bytes | None:
    """Pale placeholder PNG when chart render fails — better than a blank slide."""
    try:
        from PIL import Image, ImageDraw
        img  = Image.new("RGB", (1380, 776), color="#f8fafc")
        draw = ImageDraw.Draw(img)
        draw.rectangle([40, 40, 1340, 736], outline="#e2e8f0", width=2)
        draw.text((690, 350), "📊", anchor="mm", fill="#d1d5db")
        draw.text((690, 420), title[:70], anchor="mm", fill="#9ca3af")
        draw.text((690, 460), "Open the web app to view this chart interactively",
                  anchor="mm", fill="#d1d5db")
        buf = io.BytesIO(); img.save(buf, format="PNG"); buf.seek(0)
        return buf.getvalue()
    except Exception:
        return None


# ── Text helpers ──────────────────────────────────────────────────────────────
def _tf(shape):
    return shape.text_frame


def _para(tf, text: str, size=11, bold=False, italic=False,
          color=DARK, align=PP_ALIGN.LEFT):
    p   = tf.add_paragraph()
    p.alignment = align
    run = p.add_run()
    run.text = text
    run.font.size   = Pt(size)
    run.font.bold   = bold
    run.font.italic = italic
    run.font.color.rgb = color
    run.font.name   = "Calibri"
    return p


def _box(slide, l, t, w, h, text="", size=11, bold=False, italic=False,
         color=DARK, align=PP_ALIGN.LEFT, wrap=True):
    tb  = slide.shapes.add_textbox(l, t, w, h)
    tf  = tb.text_frame
    tf.word_wrap = wrap
    if text:
        _para(tf, text, size=size, bold=bold, italic=italic, color=color, align=align)
    return tb, tf


def _rect(slide, l, t, w, h, fill, line=False):
    s = slide.shapes.add_shape(1, l, t, w, h)
    s.fill.solid(); s.fill.fore_color.rgb = fill
    if not line: s.line.fill.background()
    s.shadow.inherit = False
    return s


# ── Slides ────────────────────────────────────────────────────────────────────
def _title_slide(prs, title: str, stats: list):
    blank = prs.slide_layouts[6]
    sl    = prs.slides.add_slide(blank)

    # Full-bleed dark background
    _rect(sl, 0, 0, W, H, NAVY)
    # Indigo accent stripe
    _rect(sl, 0, Inches(4.6), W, Inches(0.05), INDIGO)

    # Logo / app name
    _box(sl, Inches(1), Inches(1.1), Inches(11), Inches(0.55),
         "◈  HR Analytics Platform",
         size=14, color=LIGHT)

    # Report title
    _, tf = _box(sl, Inches(1), Inches(1.75), Inches(11), Inches(1.7))
    _para(tf, title, size=38, bold=True, color=WHITE)

    # Subtitle
    _box(sl, Inches(1), Inches(3.55), Inches(11), Inches(0.55),
         "People Intelligence Report", size=14, color=LIGHT)

    # Stats row — extracted from insights
    if stats:
        cell_w = Inches(11) / len(stats)
        for i, (val, lbl) in enumerate(stats):
            x = Inches(1) + i * cell_w
            _box(sl, x, Inches(4.85), cell_w, Inches(0.55),
                 str(val), size=22, bold=True, color=WHITE)
            _box(sl, x, Inches(5.42), cell_w, Inches(0.35),
                 lbl[:28], size=9, color=LIGHT)

    # Footer
    _box(sl, Inches(1), Inches(7.06), Inches(11.3), Inches(0.28),
         "Generated by HR Analytics Platform  ·  For internal use only",
         size=9, color=LIGHT)
    return sl


def _chart_slide(prs, title: str, img_bytes: bytes | None,
                 insight: str = "", number: int = 1, total: int = 1):
    """
    16:9 slide layout:
      Left 65%  — chart image (or placeholder)
      Right 35% — editable: KEY INSIGHT, ANNOTATIONS, NOTES
    All text elements are independently editable in PowerPoint.
    """
    blank = prs.slide_layouts[6]
    sl    = prs.slides.add_slide(blank)

    # ── Header bar ──────────────────────────────────────────────────────────
    _rect(sl, 0, 0, W, Inches(0.78), INDIGO)

    # Slide counter
    _box(sl, Inches(12.0), Inches(0.11), Inches(1.1), Inches(0.52),
         f"{number}/{total}",
         size=10, color=WHITE, align=PP_ALIGN.RIGHT)

    # Chart title (editable)
    _, tf_title = _box(sl, Inches(0.28), Inches(0.10), Inches(11.5), Inches(0.58))
    _para(tf_title, title, size=20, bold=True, color=WHITE)

    # ── Chart image / placeholder ────────────────────────────────────────────
    img_l = Inches(0.14); img_t = Inches(0.86)
    img_w = Inches(8.55); img_h = Inches(5.72)

    render = img_bytes or _make_placeholder_img(title)
    if render:
        try:
            sl.shapes.add_picture(io.BytesIO(render), img_l, img_t, img_w, img_h)
        except Exception:
            # Add text placeholder if image fails completely
            _box(sl, img_l, img_t, img_w, img_h,
                 f"📊 {title}\n\n(Open the app to view this chart interactively)",
                 size=14, color=LIGHT, italic=True)
    else:
        _box(sl, img_l, img_t, img_w, img_h,
             f"📊 {title}\n\n(Open the app to view this chart interactively)",
             size=14, color=LIGHT, italic=True)

    # ── Right panel ──────────────────────────────────────────────────────────
    px = Inches(8.83); pw = Inches(4.35)

    # KEY INSIGHT label
    _box(sl, px, Inches(0.90), pw, Inches(0.32),
         "KEY INSIGHT", size=8, bold=True, color=LIGHT)

    # Insight text (editable) — full height, word-wrapped
    _, tf_ins = _box(sl, px, Inches(1.24), pw, Inches(2.30), wrap=True)
    _para(tf_ins,
          insight if insight else "Add your interpretation here.",
          size=11, italic=True, color=DARK)

    # Divider
    _rect(sl, px, Inches(3.60), pw, Inches(0.025), SILVER)

    # ANNOTATIONS label
    _box(sl, px, Inches(3.66), pw, Inches(0.32),
         "ANNOTATIONS / ACTIONS", size=8, bold=True, color=LIGHT)

    # Annotation area (editable, pre-filled with prompt)
    _, tf_ann = _box(sl, px, Inches(4.00), pw, Inches(2.10), wrap=True)
    _para(tf_ann,
          "• Click to add action items\n"
          "• Add context specific to your organisation\n"
          "• Note any follow-up required",
          size=10, color=MID)

    # ── Bottom strip ─────────────────────────────────────────────────────────
    _rect(sl, 0, Inches(6.60), W, Inches(0.03), SILVER)

    # Notes area (left, editable)
    _, tf_notes = _box(sl, Inches(0.18), Inches(6.66), Inches(8.55), Inches(0.70))
    _para(tf_notes, "Notes:", size=8, bold=True, color=MID)
    _para(tf_notes, "Click to add presenter notes for this chart.", size=10, color=LIGHT)

    return sl


def _summary_slide(prs, insights_list: list):
    """Key Findings slide — all text is editable."""
    blank = prs.slide_layouts[6]
    sl    = prs.slides.add_slide(blank)

    _rect(sl, 0, 0, W, Inches(0.83), NAVY)
    _box(sl, Inches(0.35), Inches(0.11), Inches(12.6), Inches(0.62),
         "Key Findings Summary", size=24, bold=True, color=WHITE)

    if not insights_list:
        _box(sl, Inches(0.5), Inches(1.2), Inches(12.3), Inches(5.5),
             "Add your key findings here.", size=14, color=DARK)
    else:
        col_w = Inches(6.18); gutter = Inches(0.28)
        rx, ry = Inches(0.35), Inches(1.0)
        lx, ly = rx, ry

        for idx, item in enumerate(insights_list[:10]):
            emoji, headline, detail = (item if len(item)==3 else (item[0], item[1], ""))
            detail = detail[:160] + ("…" if len(detail)>160 else "")

            x = lx if idx % 2 == 0 else rx + col_w + gutter
            y = ly if idx % 2 == 0 else ry
            card_h = Inches(0.92)

            # Card background
            _rect(sl, x, y, col_w, card_h, ACCENT_LIGHT)
            # Indigo left stripe
            _rect(sl, x, y, Inches(0.055), card_h, INDIGO)

            # Headline
            _, tf1 = _box(sl, x+Inches(0.14), y+Inches(0.06), col_w-Inches(0.2), Inches(0.36))
            _para(tf1, f"{emoji}  {headline}", size=11, bold=True, color=DARK)

            # Detail
            _, tf2 = _box(sl, x+Inches(0.14), y+Inches(0.44), col_w-Inches(0.2), Inches(0.40))
            _para(tf2, detail, size=9, color=MID)

            if idx % 2 == 0: ly += Inches(1.0)
            else:             ry += Inches(1.0)

    # Footer
    _rect(sl, 0, Inches(7.18), W, Inches(0.32), NAVY)
    _box(sl, Inches(0.35), Inches(7.20), Inches(12.6), Inches(0.25),
         "HR Analytics Platform  ·  All text in this report is editable in PowerPoint",
         size=8, color=LIGHT)
    return sl


# ── Public API ────────────────────────────────────────────────────────────────
def build_pptx(selections: list,
               report_title: str = "HR Analytics Report",
               insights_list: list = None) -> bytes:
    """Build editable PPTX: title slide + one chart slide per selection + summary."""
    prs = Presentation()
    prs.slide_width  = W
    prs.slide_height = H

    # Extract clean stats for title slide
    stats = []
    clean_num = re.compile(r'([\d,]+(?:\.\d+)?%?(?:pp|K|M)?)')
    for item in selections[:6]:
        ins = item.get("insight","")
        nums = [n.rstrip('.,;:') for n in clean_num.findall(ins)]
        if nums:
            stats.append((nums[0], item.get("title","")[:28]))
    if not stats and insights_list:
        for emoji, headline, detail in (insights_list or [])[:4]:
            nums = [n.rstrip('.,;:') for n in clean_num.findall(headline+detail)]
            if nums: stats.append((nums[0], headline[:28]))

    _title_slide(prs, report_title, stats[:5])

    total = len(selections)
    for i, item in enumerate(selections, 1):
        img = fig_to_png(item.get("fig"))
        _chart_slide(prs,
                     title   = item.get("title", f"Chart {i}"),
                     img_bytes = img,
                     insight = item.get("insight",""),
                     number  = i,
                     total   = total)

    _summary_slide(prs, insights_list or [])

    out = io.BytesIO(); prs.save(out); out.seek(0)
    return out.getvalue()


def build_excel(df, col_map: dict, insights_list: list = None) -> bytes:
    """3-sheet formatted Excel: Employee Data, KPI Summary, Column Mapping."""
    import pandas as pd
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    buf  = io.BytesIO()
    skip = {c for c in df.columns if c.startswith("__")}
    df_exp = df[[c for c in df.columns if c not in skip]].copy()
    for col in df_exp.columns:
        if pd.api.types.is_datetime64_any_dtype(df_exp[col]):
            df_exp[col] = df_exp[col].dt.date

    # KPI summary rows
    rows = []
    n = len(df)
    ac = col_map.get("_is_active","__is_active")
    at = col_map.get("_attrition"); te = col_map.get("_tenure_years")
    gn = col_map.get("gender");     sl = next((col_map.get(c) for c in ["salary"] if col_map.get(c)), None)
    rows.append(("Total Records", n, "All records in filter"))
    if ac in df.columns:
        act = int((df[ac]==1).sum())
        rows.append(("Active Employees", act, f"{act/n:.1%} of total"))
        rows.append(("Former Employees", n-act, f"{(n-act)/n:.1%} of total"))
    if at and at in df.columns:
        rows.append(("Attrition Rate", f"{df[at].mean():.1%}", "15% = industry benchmark"))
    if te and te in df.columns:
        rows.append(("Avg Tenure (yrs)", round(df[te].mean(),1), ""))
    if gn and gn in df.columns:
        rows.append(("Female %", f"{(df[gn]=='Female').mean():.1%}", "30% = D&I target"))
    if sl and sl in df.columns:
        rows.append(("Median Pay", f"{df[sl].median():,.0f}", ""))
    for emoji,h,d in (insights_list or []):
        rows.append((f"{emoji} {h}", "", d[:120]))

    kpi_df = pd.DataFrame(rows, columns=["Metric","Value","Note"])
    map_df = pd.DataFrame([(k.replace("_"," ").title(), v) for k,v in col_map.items()
                            if not k.startswith("_")], columns=["HR Concept","Detected Column"])

    with pd.ExcelWriter(buf, engine="openpyxl") as writer:
        df_exp.to_excel(writer, sheet_name="Employee Data",  index=False)
        kpi_df.to_excel(writer, sheet_name="KPI Summary",    index=False)
        map_df.to_excel(writer, sheet_name="Column Mapping", index=False)
        wb = writer.book
        HF = PatternFill("solid", fgColor="5046E4")
        AF = PatternFill("solid", fgColor="EEF2FF")
        HN = Font(name="Calibri", bold=True, color="FFFFFF", size=11)
        BN = Font(name="Calibri", size=11, color="111827")
        BS = Border(bottom=Side(style="thin", color="E2E8F0"))

        def _style(ws, widths=None):
            for c in ws[1]:
                c.font=HN; c.fill=HF
                c.alignment=Alignment(horizontal="center", vertical="center")
            for ri,row in enumerate(ws.iter_rows(min_row=2), 2):
                for c in row:
                    c.font=BN; c.border=BS
                    c.alignment=Alignment(horizontal="left", vertical="center", wrap_text=True)
                    if ri%2==0: c.fill=AF
            if widths:
                for col_letter, w in widths.items():
                    ws.column_dimensions[col_letter].width=w
            else:
                for col in ws.columns:
                    mw=max((len(str(c.value or "")) for c in col), default=8)
                    ws.column_dimensions[col[0].column_letter].width=min(mw+4,40)
            ws.freeze_panes="A2"; ws.row_dimensions[1].height=22

        _style(wb["Employee Data"])
        _style(wb["KPI Summary"],    {"A":"32","B":"18","C":"50"})
        _style(wb["Column Mapping"], {"A":"26","B":"32"})
        wb["Employee Data"].auto_filter.ref = wb["Employee Data"].dimensions

    buf.seek(0)
    return buf.getvalue()
